"""add strava tokens to user

Revision ID: 18a9fbdf0ea0
Revises: 
Create Date: 2026-04-30 15:48:55.675549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a9fbdf0ea0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strava_access_token', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('strava_refresh_token', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('strava_token_expires_at', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('strava_token_expires_at')
        batch_op.drop_column('strava_refresh_token')
        batch_op.drop_column('strava_access_token')

    # ### end Alembic commands ###
