"""add saved_plan table

Revision ID: 2a5672e570ad
Revises: 18a9fbdf0ea0
Create Date: 2026-05-29 15:43:28.989924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5672e570ad'
down_revision = '18a9fbdf0ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strava_athlete_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('plan_json', sa.Text(), nullable=False),
    sa.Column('race_name', sa.String(length=100), nullable=True),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strava_athlete_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_plan')
    # ### end Alembic commands ###
